export type TEquipment = {
    id: number,
    No: number,
    doc_title: string,
    manufacturer: string | null,
    validation_place: string | null,
    validation_cost: number | null,
    inventory_number: string,
    k_v_a: string | null,
    no_certificate: string | null,
    last_verification_date: number | null,
    checking_manometers: number | null,
    next_verification_date: number | null,
    notes: string | null,
    actual: number,
}